### ISSUE TITLE
$465 and $466 

### ISSUE THREAD

**Issue by GameOEver** [grblHAL/Plugins_spindle#23]
Hello, 

i am trying to get a SIEMENS VFD running but $465 and $466 seem to only accept values up to 255.

In my case the CW and CCW commands would be 1151 and 3199 sice the vfd uses bit 11 for direction.

If i set $465 and $466  to the values 1151 and 3199 it always writes 127 to the modbus register.

Is there any workaround for that?

Thanks in advance!

**Comment by terjeio** [comment]
Which version (from $I output)?
I committed a fix 20230130 in my local repo so should be ok in the latest from github.

**Comment by GameOEver** [comment]
$1 gives me 25 as output

**Comment by terjeio** [comment]
$I not $1...

**Comment by GameOEver** [comment]
my bad, was on my way to work. Will check that later.

**Comment by GameOEver** [comment]
Hello, 

the firmware of my controller had an older firmware in it. Updating it to the latest beta pre-release solved the issue.

Thank you
