### ISSUE TITLE
Stream claiming logic with MODBUS_RTU_STREAM defined

### ISSUE THREAD

**Issue by dresco** [grblHAL/Plugins_spindle#25]
Hi,

Am wondering whether there is an error with the current logic for claiming serial streams?

Have been looking at the F7 driver, and as best as I can see, the `instance` member checked in the following code is always 0,1, or 2 - and not the number from the SERIALn_PORT / MODBUS_RTU_STREAM definition? 

https://github.com/grblHAL/Plugins_spindle/blob/7056c25b302f0719dd3ac1c52e8bb0a1b4624463/modbus_rtu.c#L501-L505

I've been trying to verify this with the F7/H7 Nucleo reference map;

- Without MODBUS_RTU_STREAM defined, it takes the first available stream which works fine.
- With MODBUS_RTU_STREAM defined as SERIAL1_PORT, this also works but I think just coincidentally? As SERIAL1_PORT is defined in the reference map as 1.
- If  SERIAL1_PORT is defined as something else (say 11, or 2, or 21), this will result in a `[MSG:Warning: Modbus failed to initialize!]` error, and then becomes unresponsive.
- Same story if MODBUS_RTU_STREAM / SERIAL2_PORT is used instead. Works fine if defined as 2, but not 1/11/21 etc.

**Comment by terjeio** [comment]
Have been looking at the F7 driver, and as best as I can see, the instance member checked in the following code is always 0,1, or 2 - and not the number from the SERIALn_PORT / MODBUS_RTU_STREAM definition?

Correct. The SERIALn_PORT definition binds a physical port to an instance at the driver level. Outside of the serial driver code the [port instance](https://github.com/grblHAL/STM32F4xx/blob/019dc048242a669da8866ff7c01e21e60bfecac7/Src/serial.c#L315) is used to connect to the port.

**Comment by dresco** [comment]
Thanks, so instead of this (for instance)
```
#define SERIAL1_PORT                32 // GPIOD: TX =  8, RX =  9
#define MODBUS_RTU_STREAM           SERIAL1_PORT
```

The expected way would be like this?
```
#define SERIAL1_PORT                32 // GPIOD: TX =  8, RX =  9
#define MODBUS_RTU_STREAM           3
```

**Comment by terjeio** [comment]
[SERIAL1_PORT is for instance #1](https://github.com/grblHAL/STM32F4xx/blob/019dc048242a669da8866ff7c01e21e60bfecac7/Src/serial.c#L324C1-L327C21) so  `#define MODBUS_RTU_STREAM 1` is the correct definition. 
`#define SERIAL1_PORT 32` is for binding MCU UART peripheral 3 with the second (2) pin map to instance 1.

**Comment by dresco** [comment]
Ah yes sorry. Got it now, thanks!
