### ISSUE TITLE
modbus_rtu receives zero length packet

### ISSUE THREAD

**Issue by Nick507** [grblHAL/Plugins_spindle#26]
![image](https://github.com/grblHAL/Plugins_spindle/assets/53602873/a0a9ec2b-43dc-4c2d-8a95-11e19c5e3aa3)
Shouldn't rx_len be used as loop counter? Otherwise received packed has zero rx_length.

UPD: I see, that rx_len is used below, in CRC check. Ok, then we can't use it in loop. But it is very confusing to get packet in receive callback with zero length. Maybe restore packet->msg.rx_length = rx_len after CRC check?

**Comment by terjeio** [comment]
> Maybe restore packet->msg.rx_length = rx_len after CRC check?

Will add in next commit.
