### ISSUE TITLE
modbus_poll should change timeout->silent only for async packet

### ISSUE THREAD

**Issue by Nick507** [grblHAL/Plugins_spindle#27]
The risk of current implementation is to miss timeout state in modbus_send_rtu, because second call of modbus_poll will change it to silent.
Currently it works, just because modbus_poll is called from modbus_send_rtu, but this is very dangerous - in other conditions modbus_poll can be called by core main thread, because it hooks grbl.on_execute_realtime.
And I think that intention was that modbus_poll procedure handles this state transition for async packet, whereas for blocking packet timeout state will be changed to silent/idle by modbus_send_rtu code.

Proposed fix:
![image](https://github.com/grblHAL/Plugins_spindle/assets/53602873/629ff304-055d-4058-8272-ddbcad817198)

Additionally, I didn't find on_rx_exception callback for timeout case for async packet.

**Comment by terjeio** [comment]
> Currently it works, just because modbus_poll is called from modbus_send_rtu, but this is very dangerous - in other conditions modbus_poll can be called by core main thread, because it hooks grbl.on_execute_realtime.

The risk is, IMO, low since grblHAL in essence is single threaded. I'll add your test anyway since the state transition is also taken care of when the blocking loop exits.

> Additionally, I didn't find on_rx_exception callback for timeout case for async packet.

This is deliberate, async packets is intended for querying the device status and is typically sent when the real time status is requested. But since the API may be used for other devices than VFDs is should be added? And perhaps support for async timeouts should be added to the VFD drivers too?

**Comment by Nick507** [comment]
`This is deliberate, async packets is intended for querying the device status and is typically sent when the real time status is requested`
My understanding was that async call differs from sync call just by **non-blocking** waiting for result, but result of operation is important and must be equal for async/sync from API perspective.
Using async in VFD to request current speed (when TO result is not important) is just a particular use case.
Anyway, I just pointed that, and I think it will be better to create a separate issue, if you agree.

**Comment by terjeio** [comment]
A new issue is ok - provinding the timeout callback is easy, how it should be handled is another story. Retry or not? Generate an alarm and in which circumstances? ...

**Comment by terjeio** [comment]
I did not add the async timeout callback since I did not (and still do not) have a clear idea how to handle it at the client side.
BTW my plan is to move the RTU code to the core to make the API generally available, not bound to the spindle plugin.
