### ISSUE TITLE
Compile warning on the latest code

### ISSUE THREAD

**Issue by boboxx** [grblHAL/Plugins_spindle#33]
main/spindle/select.c: In function 'spindle_select_config':
main/spindle/select.c:448:31: warning: assignment to 'user_mcode_check_ptr' {aka 'enum <anonymous> (*)(enum <anonymous>)'} from incompatible pointer type 'user_mcode_t (*)(user_mcode_t)' {aka 'enum <anonymous> (*)(enum <anonymous>)'} [-Wincompatible-pointer-types]
         grbl.user_mcode.check = check;

**Comment by terjeio** [comment]
Fixed already, but not yet committed. Anyway, thanks for reporting.
